function mshr_simulator()
% MSHR_SIMULATOR  Interactive step-by-step visual walkthrough of the MSHR.
%
%   Run with:  mshr_simulator
%
%   This is a *conceptual* teaching aid, not a cycle-accurate simulation
%   of rtl/mshr.sv -- it illustrates the three data-flow scenarios
%   described in docs/MSHR_README.md:
%
%     1. Read Miss        -- a load misses, MSHR fetches the line over AXI.
%     2. Write Miss        -- a store misses; identical AXI fetch, but the
%                             line comes back flagged for merge + dirty.
%     3. Writeback/Eviction -- a dirty victim line is flushed to memory,
%                             including the AXI B-channel write response.
%
%   Use the dropdown to pick a scenario and Next/Previous to step through
%   it. Each step highlights which block currently holds the data, draws
%   the AXI/internal handshake that is active, and prints the signals
%   that would be asserted at that point in rtl/mshr.sv.

    fig = figure('Name', 'MSHR & AXI Data Flow Simulator', ...
                 'NumberTitle', 'off', 'Position', [100, 100, 1000, 650], ...
                 'Color', [0.12 0.14 0.18], 'MenuBar', 'none');

    MAX_STEPS = 4;

    % Shared state, mutated by the nested callbacks below.
    appData = struct();
    appData.modeKey = 'ReadMiss';
    appData.step    = 1;

    setupUI(fig);
    updateDisplay();

    %% --- UI Setup ---
    function setupUI(parent)
        uicontrol(parent, 'Style', 'text', 'String', 'MSHR & AXI Interactive Flow Simulator', ...
                  'Position', [50, 590, 900, 40], 'FontSize', 16, 'FontWeight', 'bold', ...
                  'ForegroundColor', [1 1 1], 'BackgroundColor', [0.12 0.14 0.18]);

        uicontrol(parent, 'Style', 'text', 'String', 'Select Scenario:', ...
                  'Position', [50, 550, 110, 25], 'FontSize', 10, ...
                  'ForegroundColor', [0.8 0.8 0.8], 'BackgroundColor', [0.12 0.14 0.18], ...
                  'HorizontalAlignment', 'left');

        appData.modePopup = uicontrol(parent, 'Style', 'popupmenu', ...
                  'String', {'Read Miss', 'Write Miss', 'Writeback (Eviction)'}, ...
                  'Position', [160, 552, 190, 25], 'FontSize', 10, ...
                  'Callback', @onModeChange);

        appData.txtStep = uicontrol(parent, 'Style', 'text', 'String', '', ...
                  'Position', [400, 550, 240, 25], 'FontSize', 10, 'FontWeight', 'bold', ...
                  'ForegroundColor', [0.3 0.8 1], 'BackgroundColor', [0.12 0.14 0.18], ...
                  'HorizontalAlignment', 'center');

        appData.btnPrev = uicontrol(parent, 'Style', 'pushbutton', 'String', '< Previous', ...
                  'Position', [650, 550, 90, 30], 'FontSize', 10, 'FontWeight', 'bold', ...
                  'BackgroundColor', [0.25 0.3 0.4], 'ForegroundColor', [1 1 1], ...
                  'Callback', @(~,~) changeStep(-1));

        appData.btnNext = uicontrol(parent, 'Style', 'pushbutton', 'String', 'Next >', ...
                  'Position', [750, 550, 90, 30], 'FontSize', 10, 'FontWeight', 'bold', ...
                  'BackgroundColor', [0.1 0.5 0.8], 'ForegroundColor', [1 1 1], ...
                  'Callback', @(~,~) changeStep(1));

        uicontrol(parent, 'Style', 'pushbutton', 'String', 'Reset', ...
                  'Position', [850, 550, 70, 30], 'FontSize', 10, ...
                  'BackgroundColor', [0.4 0.2 0.2], 'ForegroundColor', [1 1 1], ...
                  'Callback', @(~,~) resetSim());

        appData.ax = axes('Parent', parent, 'Units', 'pixels', 'Position', [50, 230, 900, 300], ...
                          'Color', [0.16 0.18 0.23], 'XColor', 'none', 'YColor', 'none');
        axis(appData.ax, [0 10 0 5]);
        hold(appData.ax, 'on');

        uicontrol(parent, 'Style', 'text', 'String', 'Hardware Action & Explanation:', ...
                  'Position', [50, 190, 550, 25], 'FontSize', 11, 'FontWeight', 'bold', ...
                  'ForegroundColor', [0.3 0.8 1], 'BackgroundColor', [0.12 0.14 0.18], ...
                  'HorizontalAlignment', 'left');

        appData.txtExplain = uicontrol(parent, 'Style', 'edit', 'Max', 2, 'Min', 0, ...
                  'Position', [50, 30, 550, 150], 'FontSize', 11, ...
                  'ForegroundColor', [0.9 0.9 0.9], 'BackgroundColor', [0.18 0.2 0.26], ...
                  'HorizontalAlignment', 'left', 'Enable', 'inactive');

        uicontrol(parent, 'Style', 'text', 'String', 'Active Signals State:', ...
                  'Position', [630, 190, 320, 25], 'FontSize', 11, 'FontWeight', 'bold', ...
                  'ForegroundColor', [0.3 0.8 1], 'BackgroundColor', [0.12 0.14 0.18], ...
                  'HorizontalAlignment', 'left');

        appData.txtSignals = uicontrol(parent, 'Style', 'edit', 'Max', 2, 'Min', 0, ...
                  'Position', [630, 30, 320, 150], 'FontSize', 10, 'FontName', 'Monospaced', ...
                  'ForegroundColor', [0.2 1 0.4], 'BackgroundColor', [0.18 0.2 0.26], ...
                  'HorizontalAlignment', 'left', 'Enable', 'inactive');
    end

    %% --- Callbacks ---
    function onModeChange(src, ~)
        keys = {'ReadMiss', 'WriteMiss', 'Writeback'};
        appData.modeKey = keys{src.Value};
        appData.step = 1;
        updateDisplay();
    end

    function changeStep(delta)
        appData.step = max(1, min(MAX_STEPS, appData.step + delta));
        updateDisplay();
    end

    function resetSim()
        appData.step = 1;
        updateDisplay();
    end

    %% --- Render ---
    function updateDisplay()
        cla(appData.ax);
        hold(appData.ax, 'on');

        blocks.L1   = [0.5, 1.8, 1.8, 1.4];
        blocks.MSHR = [3.5, 1.8, 2.0, 1.4];
        blocks.AXI  = [6.2, 1.8, 1.2, 1.4];
        blocks.MEM  = [8.0, 1.8, 1.5, 1.4];

        scenario = getScenario(appData.modeKey);
        step     = appData.step;

        activeBlock = scenario.activeSeq{step};
        drawBlock(appData.ax, blocks.L1,   'Core / L1 Cache', strcmp(activeBlock, 'L1'));
        drawBlock(appData.ax, blocks.MSHR, 'MSHR Engine',     strcmp(activeBlock, 'MSHR'));
        drawBlock(appData.ax, blocks.AXI,  'AXI Bus',         strcmp(activeBlock, 'AXI'));
        drawBlock(appData.ax, blocks.MEM,  'Main Memory',     strcmp(activeBlock, 'MEM'));

        a = scenario.arrows{step};
        startP = blockEdge(blocks.(a.fromBlock), a.fromSide, a.yFrac);
        endP   = blockEdge(blocks.(a.toBlock),   a.toSide,   a.yFrac);
        drawArrow(appData.ax, startP, endP, a.label, a.color);

        set(appData.txtExplain, 'String', scenario.explanations{step});
        set(appData.txtSignals, 'String', scenario.signals{step});
        set(appData.txtStep, 'String', sprintf('%s -- Step %d of %d', scenario.name, step, MAX_STEPS));

        onoff = {'off', 'on'};
        set(appData.btnPrev, 'Enable', onoff{(step > 1) + 1});
        set(appData.btnNext, 'Enable', onoff{(step < MAX_STEPS) + 1});
    end

end

%% ===================================================================
%  Pure helpers below: no shared state, so they take every value they
%  need as an argument instead of closing over the figure's app data.
%  ===================================================================

function pt = blockEdge(pos, side, yFrac)
    % pos = [x y w h]. side = 'left' or 'right' edge of the block.
    % yFrac in [0,1] selects the vertical point on that edge.
    if strcmp(side, 'right')
        px = pos(1) + pos(3);
    else
        px = pos(1);
    end
    py = pos(2) + yFrac * pos(4);
    pt = [px, py];
end

function drawBlock(ax, pos, name, isActive)
    if isActive
        faceColor = [0.1 0.4 0.7];
        edgeColor = [0.3 0.8 1];
        lWidth = 2.5;
    else
        faceColor = [0.2 0.22 0.28];
        edgeColor = [0.4 0.4 0.5];
        lWidth = 1;
    end
    rectangle('Position', pos, 'Curvature', 0.15, 'FaceColor', faceColor, ...
              'EdgeColor', edgeColor, 'LineWidth', lWidth, 'Parent', ax);
    text(ax, pos(1)+pos(3)/2, pos(2)+pos(4)/2, name, 'Color', [1 1 1], ...
         'FontSize', 10, 'FontWeight', 'bold', 'HorizontalAlignment', 'center');
end

function drawArrow(ax, startP, endP, labelText, color)
    plot(ax, [startP(1) endP(1)], [startP(2) endP(2)], 'LineWidth', 2.5, 'Color', color);

    % Arrowhead must point the way the data is actually moving -- a
    % right-to-left transfer (e.g. memory returning read data) needs a
    % '<' marker, not the fixed '>' the original script always used.
    if endP(1) >= startP(1)
        marker = '>';
    else
        marker = '<';
    end
    plot(ax, endP(1), endP(2), marker, 'MarkerSize', 8, ...
         'MarkerFaceColor', color, 'MarkerEdgeColor', color);

    yMid = (startP(2) + endP(2)) / 2 + 0.28;
    text(ax, (startP(1)+endP(1))/2, yMid, labelText, ...
         'Color', color, 'FontSize', 9, 'FontWeight', 'bold', 'HorizontalAlignment', 'center');
end

function s = getScenario(key)
    % Single source of truth per scenario: which block lights up, what
    % arrow is drawn, and what text is shown, all live together here so
    % they cannot drift out of sync with each other step-by-step.
    switch key
        case 'ReadMiss'
            s.name = 'Read Miss';
            s.activeSeq = {'MSHR', 'AXI', 'MSHR', 'L1'};
            s.arrows = {
                arrow('L1','right', 'MSHR','left', 0.7, 'alloc\_valid, alloc\_addr, alloc\_is\_write=0', [1 0.8 0.2]), ...
                arrow('MSHR','right','AXI','left',  0.9, 'AR: arvalid, araddr, arid', [0.3 0.8 1]), ...
                arrow('MEM','left',  'MSHR','right',0.5, 'R: rdata, rid, rlast', [0.2 1 0.4]), ...
                arrow('MSHR','left', 'L1','right',  0.3, 'fill\_valid, fill\_data, fill\_is\_write=0', [1 0.4 0.8])};
            s.explanations = {
                sprintf(['STEP 1: Read Miss Allocation\n' ...
                         '- The Core/L1 Cache requests address 0x1000 and misses.\n' ...
                         '- The miss is reported to the MSHR (alloc_valid/alloc_addr).\n' ...
                         '- MSHR finds no in-flight entry for this address, allocates a\n' ...
                         '  free entry, and assigns alloc_id = 2.']), ...
                sprintf(['STEP 2: AXI Read Address (AR Channel)\n' ...
                         '- MSHR issues a read burst request to memory.\n' ...
                         '- Drives arvalid=1, araddr=0x1000, arid=2, arlen=3 (4 beats).\n' ...
                         '- Memory accepts the request once arready=1.']), ...
                sprintf(['STEP 3: AXI Read Data Burst (R Channel)\n' ...
                         '- Memory streams the line back as 4 beats on rdata.\n' ...
                         '- Every beat carries rid=2 so the MSHR reassembles it into\n' ...
                         '  the correct entry''s line buffer; rlast marks beat 4.']), ...
                sprintf(['STEP 4: Cache Fill & Completion\n' ...
                         '- MSHR presents the reassembled 128-bit line to the controller\n' ...
                         '  via fill_valid/fill_data (fill_is_write=0, this was a load).\n' ...
                         '- The controller writes the line into the data array.\n' ...
                         '- Entry 2 returns to IDLE, free for a future miss.'])};
            s.signals = {
                sprintf('alloc_valid = 1\nalloc_addr  = 0x1000\nalloc_is_write = 0\nalloc_ready = 1\nalloc_id    = 2'), ...
                sprintf('axi.arvalid = 1\naxi.araddr  = 0x1000\naxi.arid    = 2\naxi.arlen   = 3\naxi.arready = 1'), ...
                sprintf('axi.rvalid  = 1\naxi.rdata   = [word i]\naxi.rid     = 2\naxi.rready  = 1\naxi.rlast   = 1 (beat 3)'), ...
                sprintf('fill_valid    = 1\nfill_id       = 2\nfill_is_write = 0\nfill_data     = [128-bit line]\nEntry state   = IDLE')};

        case 'WriteMiss'
            s.name = 'Write Miss';
            s.activeSeq = {'MSHR', 'AXI', 'MSHR', 'L1'};
            s.arrows = {
                arrow('L1','right', 'MSHR','left', 0.7, 'alloc\_valid, alloc\_addr, alloc\_is\_write=1', [1 0.8 0.2]), ...
                arrow('MSHR','right','AXI','left',  0.9, 'AR: same fetch as a read miss', [0.3 0.8 1]), ...
                arrow('MEM','left',  'MSHR','right',0.5, 'R: original (pre-store) line data', [0.2 1 0.4]), ...
                arrow('MSHR','left', 'L1','right',  0.3, 'fill\_is\_write=1 -> line marked DIRTY', [1 0.3 0.3])};
            s.explanations = {
                sprintf(['STEP 1: Write Miss Allocation\n' ...
                         '- The Core stores to address 0x3000, missing in L1 (this\n' ...
                         '  design is write-allocate: a store miss still fetches the line).\n' ...
                         '- alloc_is_write=1 is reported; MSHR opens entry 5 and\n' ...
                         '  remembers this entry must come back flagged dirty.']), ...
                sprintf(['STEP 2: AXI Read Address (AR Channel)\n' ...
                         '- The MSHR does not special-case write misses at the AXI level\n' ...
                         '  -- it still issues a normal 4-beat read burst (arid=5), because\n' ...
                         '  it must have the *rest* of the line before it can merge one\n' ...
                         '  store into it.']), ...
                sprintf(['STEP 3: AXI Read Data Burst (R Channel)\n' ...
                         '- Memory returns the line as it currently exists in DRAM --\n' ...
                         '  the pending store has not been applied yet.\n' ...
                         '- MSHR reassembles these 4 beats exactly as for a read miss.']), ...
                sprintf(['STEP 4: Dirty Fill & Store Merge\n' ...
                         '- MSHR hands the line to the controller with fill_is_write=1.\n' ...
                         '- The controller merges the Core''s pending store into the line\n' ...
                         '  and marks it DIRTY in the tag array.\n' ...
                         '- This is how a dirty line is born -- it will need a Writeback\n' ...
                         '  before it can ever be evicted (see that scenario).'])};
            s.signals = {
                sprintf('alloc_valid    = 1\nalloc_addr     = 0x3000\nalloc_is_write = 1\nalloc_id       = 5'), ...
                sprintf('axi.arvalid = 1\naxi.araddr  = 0x3000\naxi.arid    = 5\naxi.arlen   = 3'), ...
                sprintf('axi.rvalid = 1\naxi.rdata  = [old word i]\naxi.rid    = 5\naxi.rlast  = 1 (beat 3)'), ...
                sprintf('fill_valid    = 1\nfill_id       = 5\nfill_is_write = 1\nCache line state = DIRTY')};

        case 'Writeback'
            s.name = 'Writeback (Eviction)';
            s.activeSeq = {'MSHR', 'AXI', 'MEM', 'MSHR'};
            s.arrows = {
                arrow('L1','right', 'MSHR','left', 0.7, 'wb\_valid, wb\_addr, wb\_data (dirty line)', [1 0.5 0.2]), ...
                arrow('MSHR','right','AXI','left',  0.9, 'AW: awvalid, awaddr', [0.3 0.8 1]), ...
                arrow('MSHR','right','MEM','left',  0.5, 'W: wdata beats 0-3, wlast', [1 0.8 0.2]), ...
                arrow('MEM','left',  'MSHR','right',0.2, 'B: bvalid, bresp=OKAY -> wb\_done', [0.2 1 0.4])};
            s.explanations = {
                sprintf(['STEP 1: Victim Handed to the MSHR\n' ...
                         '- The replacement policy evicts a dirty line at 0x2000 to make\n' ...
                         '  room for an incoming fill.\n' ...
                         '- The controller hands it to the MSHR (wb_valid/wb_addr/wb_data);\n' ...
                         '  it is queued so the cache slot is freed immediately --\n' ...
                         '  the Core does not stall waiting for the write to finish.']), ...
                sprintf(['STEP 2: AXI Write Address (AW Channel)\n' ...
                         '- MSHR drains the queue one victim at a time and issues the\n' ...
                         '  write address: awvalid=1, awaddr=0x2000.\n' ...
                         '- Memory accepts the request when awready=1.']), ...
                sprintf(['STEP 3: AXI Write Data Burst (W Channel)\n' ...
                         '- MSHR streams the 4 dirty words to memory: wvalid=1, wdata,\n' ...
                         '  wlast=1 on the final beat.\n' ...
                         '- Data now flows MSHR -> memory -- the *opposite* direction\n' ...
                         '  from a read''s R channel.']), ...
                sprintf(['STEP 4: AXI Write Response (B Channel)\n' ...
                         '- Memory reports back: bvalid=1, bresp=OKAY.\n' ...
                         '- Why does a WRITE need this extra channel but a READ does not?\n' ...
                         '  Read data already flows memory->MSHR on R, so a status code\n' ...
                         '  can just ride along with it. W only flows MSHR->memory --\n' ...
                         '  there is no wire on that channel pointing back. B exists purely\n' ...
                         '  to carry that acknowledgement the other way.\n' ...
                         '- Only once B arrives can wb_done pulse and the queue slot free --\n' ...
                         '  until then this is the only surviving copy of the dirty data.'])};
            s.signals = {
                sprintf('wb_valid = 1\nwb_addr  = 0x2000\nwb_data  = [dirty line]\nwb_ready = 1'), ...
                sprintf('axi.awvalid = 1\naxi.awaddr  = 0x2000\naxi.awready = 1'), ...
                sprintf('axi.wvalid = 1\naxi.wdata  = [word i]\naxi.wready = 1\naxi.wlast  = 1 (beat 3)'), ...
                sprintf('axi.bvalid = 1\naxi.bresp  = 2''b00 (OKAY)\naxi.bready = 1\nwb_done    = 1 (pulse)\nWB slot    = FREED')};

        otherwise
            error('mshr_simulator:unknownScenario', 'Unknown scenario key: %s', key);
    end
end

function a = arrow(fromBlock, fromSide, toBlock, toSide, yFrac, label, color)
    a.fromBlock = fromBlock;
    a.fromSide  = fromSide;
    a.toBlock   = toBlock;
    a.toSide    = toSide;
    a.yFrac     = yFrac;
    a.label     = label;
    a.color     = color;
end
